[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
solc_version = "0.8.36"
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 256

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
